dist: trusty
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_COVERAGE=On

script:
  - make
  - ctest --verbose
  - make gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
